### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by b-thebest** [hrt/YppPokerBot#2]
Can you please write about how to use it after opening the puzzlePirates game? How to run in Ubuntu or windows 64bit

**Comment by hrt** [comment]
Simple as the install/run mentioned on the read me whilst the game is open.

This is for windows only.

**Comment by b-thebest** [comment]
What is the significance of hand_picker file here, please explain. If it can be ommited, how it will affect working?
Thanks

**Comment by hrt** [comment]
@b-thebest the hand picker is used to let you visually pick which cards to call with in preflop
